trigger:
  branches:
    include:
    - master
variables:
- name: buildConfiguration
  value: 'Release'
- name: dotNetFramework
  value: 'net7.0'
- name: dotNetVersion
  value: '7.0.x'
- name: targetRuntime
  value: 'win-x86'
stages:
- stage: __default
  jobs:
  - job: Job
    pool:
      vmImage: windows-latest
    steps:
    - task: UseDotNet@2
      inputs:
        version: $(dotNetVersion)
        includePreviewVersions: true
    - task: DotNetCoreCLI@2
      name: "Build"
      inputs:
        command: 'build'
        projects: '**/DameChales.API.App.csproj'
    - task: DotNetCoreCLI@2
      inputs:
        command: 'publish'
        publishWebProjects: false
        projects: '**/DameChales.API.App.csproj'
        arguments: '--configuration $(BuildConfiguration) --self-contained --runtime $(targetRuntime) --output $(Build.ArtifactStagingDirectory)/api'
        modifyOutputPath: false
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/api'
        ArtifactName: 'API'
        publishLocation: 'Container'

